### ISSUE TITLE
fts_fuzzy_match: update JavaScript implementation to version 0.2.0

### ISSUE THREAD

**Issue by forrestthewoods** [forrestthewoods/lib_fts#11]
Version 0.2.0 of fts_fuzzy_match makes a pretty difference in result quality. It now performs an exhaustive search to find the highest scoring match.

The JavaScript implementation is still on Version 0.1.0. If there is any demand I'll update the port. Does anyone actually use this? If yes I'll take the time to do so. Consider this an opportunity for your voice to be heard!

**Comment by rexpan** [comment]
@forrestthewoods Thank you for update this. 
If you have time, please port 0.2.0 to Javascript or write a post about the update.

**Comment by forrestthewoods** [comment]
Rather than write a new post about the update I added a new comment to my original blog post. https://medium.com/forrest-the-woods/reverse-engineering-sublime-text-s-fuzzy-match-4cffeed33fdb

**Comment by lsei** [comment]
I would also appreciate an update to the JS version!

**Comment by octavian-nita** [comment]
Oh yes, I would also love that! From a readability point of view I think it would do great good. I was actually planning to re-implement it myself but my C++ skills have yet to be refreshed -- I am still trying to fully grasp the C++ implementation :)

P.S. I am also working on a Java port, hence my interest!

**Comment by tajmone** [comment]
For your own information, @nrgwsth has published the updated version 0.2.0 of the algorithm, which can now be found here:

- https://github.com/tajmone/fuzzy-search/tree/master/fts_fuzzy_match/0.2.0/js/

I see he also made a PR here for the JS update (PR #19).

For more details, see: tajmone/fuzzy-search#10
