### ISSUE TITLE
Test examples?

### ISSUE THREAD

**Issue by fletcher** [forrestthewoods/lib_fts#16]
My apologies if I missed this in the source/documentation.

I saw that you have test data for running a query against various wordlists.  But do you have set of test examples for ensuring the accuracy of the algorithm (e.g. unit testing/test-driven development sort of thing.)??

I implemented my own algorithm using your post as an example, and saw that you updated it 2 years ago.  I never put my algorithm into production, but am now revisiting it and will be tweaking the scoring parameters and rules to try and improve results (and adding the exhaustive search approach is probably something I should do).  While updating my code, I am trying to incorporate various examples into my unit testing to ensure that new improvements don't break anything, as well as to allow me to ensure accurate results.

If others have useful examples, I would like to incorporate them to help ensure my own algorithm behaves reasonably.

Thanks, and thanks for a great post!!

**Comment by forrestthewoods** [comment]
There's no tests of any kind. Neither unit tests nor TDD. It's not a bad idea. But it's unlikely to be something I ever do.
