### ISSUE TITLE
Documentation License?

### ISSUE THREAD

**Issue by tajmone** [forrestthewoods/lib_fts#18]
Hi Forrest,

first of all, thanks for this great and inspiring project and for the generous public domain attribution!

I wanted to ask you about whether the documentation (specifically, the `fuzzy_match.md` doc) is also public domain and can be therefore reused in other projects (with due credits), or if the public domain license only applies to the code.

I'm working on an open source project on fuzzy search algorithms which will be reusing the `fts_fuzzy_match` code, and I would like to include also your `fuzzy_match.md` document, but before doing so I wanted to make sure it's alright with you.

**Comment by tajmone** [comment]
@forrestthewoods , I've included the  `fuzzy_match.md` doc in a project I've just created:

https://github.com/tajmone/fuzzy-search/blob/master/fts_fuzzy_match/fuzzy_match.md

I hope this is OK with you. I didn't alter the document, not knowing its license, and added a disclaimer:

> The __lib_fts__ repository doesn't explicitly mention if this license also applies to documentation files; so I can't vouch that the `fuzzy_match.md` document is also into the public domain. I've nevertheless decided to include it (_as is_) in this project for completion and fairness sake, and to shield the original author from any inaccuracies I might have introduced in my own documentation of his algorithms and projects.

Since the whole project revolves around your __fts_fuzzy_match__ algorithm, I though it made sense to also include the original documentation. Of course, I'm ready to amend it if this is a problem.

**Comment by forrestthewoods** [comment]
That's completely fine.
