### ISSUE TITLE
Add a proper license

### ISSUE THREAD

**Issue by dougthor42** [forrestthewoods/lib_fts#2]
Love the project, but you probably want to add a proper license.
- The Open Source Initiate suggests [not using Public Domain](https://opensource.org/faq#public-domain)
- [Why the Public Domain Isn’t a License](http://www.rosenlaw.com/lj16.htm)

Slap the [MIT License](https://opensource.org/licenses/MIT) there and you're good to go.

**Comment by forrestthewoods** [comment]
The actual license embedded in the source is:

> This software is dual-licensed to the public domain and under the following license: you are granted a perpetual, irrevocable license to copy, modify, publish, and distribute this file as you see fit.

I've updated the readme to make this clear.

**Comment by dougthor42** [comment]
Ah yes, I didn't see that. Perfect!

Sorry to bug you :smile:
