### ISSUE TITLE
Thank you :)

### ISSUE THREAD

**Issue by LeXXik** [forrestthewoods/lib_fts#26]
Not really an issue ! 

Just wanted to thank you for all the math magic on solving ballistic trajectories. If you don't mind, I ported your solution to AssemblyScript, so it can be used as a WASM binary - you can [find it here](https://github.com/LeXXik/ballistics). I made it so that your methods are abstracted away into a core binary, while other implementations may use it. This way it can be agnostic of what web 3D engine it is used with and each can do their own implementation for a tight integration. Currently added an implementation with Playcanvas. 

Cheers!

**Comment by forrestthewoods** [comment]
Thanks! I appreciate it.
