### ISSUE TITLE
Permission to use it under LGPL v2 in KDE

### ISSUE THREAD

**Issue by Waqar144** [forrestthewoods/lib_fts#29]
Hi, 

I just made a proposal in Kate Text Editor to use this library for fuzzy filtering in quick-open. Its being considered for general use in KDE and I would just like to ask that if you would be okay if we publish it under LGPL V2

The merge request is here: https://invent.kde.org/utilities/kate/-/merge_requests/140

**Comment by forrestthewoods** [comment]
Approved.

**Comment by christoph-cullmann** [comment]
Thanks for approving this.

To avoid future issues, we use this as copyright:

/*
    SPDX-FileCopyrightText: 2017 Forrest Smith
    SPDX-FileCopyrightText: 2020 Waqar Ahmed

    SPDX-License-Identifier: LGPL-2.0-or-later
*/

in our implementation, I hope the v2+ is ok, too?

**Comment by forrestthewoods** [comment]
All good.

**Comment by christoph-cullmann** [comment]
Thanks!
