### ISSUE TITLE
Bogus “licence” statement

### ISSUE THREAD

**Issue by mirabilos** [forrestthewoods/lib_fts#30]
>    This software is dual-licensed to the public domain and under the following license: you are granted a perpetual, irrevocable license to copy, modify, publish, and distribute this file as you see fit.

This is not possible. A work that _can_ fall under copyright law is always **either** in the Public Domain **or** under copyright protection, for any single given legislation. If it’s in the Public Domain, it is **not possible** to issue a licence for it, because a licence can only be given if it’s under copyright protection (therefore eroding your statement that it’s in the Public Domain… which is not possible for works with still-living authors in many parts of the world anyway).

Your best bet is to change this to a [CC0 licence](https://creativecommons.org/publicdomain/zero/1.0/legalcode) which triggers as soon as there is copyright protection in the residence of _licensee_ (not licensor), which is important.

**Comment by mirabilos** [comment]
Closing this does not make the legal invalidity of your so-called “license” go away, mind you.

**Comment by forrestthewoods** [comment]
Dual-license as Unlicense and MIT is a common pattern. See ripgrep as an example. https://github.com/BurntSushi/ripgrep

This repository was originally styled off stb_*. IIRC that was originally just public domain. But that made lawyers uncomfortable so he converted to a dual-license.

I may go through my repos and make them uniformly Unlicense + MIT. But given that Unlicense dedicates a work to the public domain I don’t believe you’ll be happy with that either.

**Comment by mirabilos** [comment]
Forrest Smith dixit:

>Dual-license as Unlicense and MIT is a common pattern.

Doesn’t make it legally doable.

>This repository was originally styled off stb_*. IIRC that was
>originally just public domain. But that made lawyers uncomfortable so

Public Domain dedications are only valid in the country of
the author (if even there), not of the recipient. They are
also not possible for most EU citizens, for example, since
copyright in most EU states is not waivable.

>I may go through my repos and make them uniformly Unlicense + MIT.

Just do CC0. It includes both a better PD dedication *and*
a suitable fallback licence *and* has wording that avoids
the problem here:

I’d be happy with MIT as well, but a licence grant and a
PD dedication cannot just stand; PD is also not a licence
(nor is the “Unlicense” which, in my country, is proprietary
nōn-free because its grant is not valid) so it cannot be
a part of a dual-licence scheme.

CC0 is a very interesting case: it does not licence the work
itself. Rather, it licences the right to licence the work.
It’s also not a simple PD dedication but a waiver (acknowledge
the work is copyrighted, then waive what can and licence the
rest, if any).

Sorry for being haphazard in writing this mail, I currently
am under a headache. If it doesn’t make sense, write back.

bye,
//mirabilos
-- 
I believe no one can invent an algorithm. One just happens to hit upon it
when God enlightens him. Or only God invents algorithms, we merely copy them.
If you don't believe in God, just consider God as Nature if you won't deny
existence.		-- Coywolf Qi Hunt
