### ISSUE TITLE
CAMEL_BONUS is mistakenly added in JavaScript version 

### ISSUE THREAD

**Issue by gyk** [forrestthewoods/lib_fts#31]
`neighbor === neighbor.toLowerCase()` evaluates to true for separators ('_' and space), so an uppercase letter following`'_'` or `' '` will get `CAMEL_BONUS` as well as `SEPARATOR_BONUS`. This is different from the C++ version where `::islower(neighbor)` is false for non-alphabetic characters.

**Comment by forrestthewoods** [comment]
Good catch! Can you submit a pull request with a fix?
