### ISSUE TITLE
solve_ballistic_arc - does not work

### ISSUE THREAD

**Issue by Sn-a-ke** [forrestthewoods/lib_fts#33]
**solve_ballistic_arc** 
the resulting vector is not equal in length to the specified speed 

https://i.imgur.com/OE4pf7G.png
and
https://i.imgur.com/uIVhWrO.png

**Comment by forrestthewoods** [comment]
Whoa. So that issue was fixed a long time ago. However fts_ballistic_trajectory.cs exists in the repo in two places, and only one of them was fixed. Whoopsies!

Thanks for the callout.
